#!/bin/bash

# Load config
. /etc/sysconfig/ssh

# Generate keys
if [ -d /config/keycache ]; then
    cp -v /config/keycache/* /etc/ssh/
else
    /usr/sbin/sshd-gen-keys-start
    mkdir -pv /config/keycache
    cp -v /etc/ssh/ssh_host_key /config/keycache/
    cp -v /etc/ssh/ssh_host_key.pub /config/keycache/
    cp -v /etc/ssh/ssh_host_dsa_key /config/keycache/
    cp -v /etc/ssh/ssh_host_dsa_key.pub /config/keycache/
    cp -v /etc/ssh/ssh_host_rsa_key /config/keycache/
    cp -v /etc/ssh/ssh_host_rsa_key.pub /config/keycache/
    cp -v /etc/ssh/ssh_host_ecdsa_key /config/keycache/
    cp -v /etc/ssh/ssh_host_ecdsa_key.pub /config/keycache/
    echo "Keys generated and stored in /config/keycache."
    echo "Map /config to a writeable directory on the host"
    echo "to ensure the SSH host keys do not change"
fi

# Run SSHD
/usr/sbin/sshd $SSHD_OPTS

# Wait for /run/sshd.pid to appear and copy it.
while [ ! -e /run/sshd.pid ]; do
  echo "Waiting for /run/sshd.pid to appear..."
  sleep 1
done
cp /run/sshd.pid /run/watch/sshd

