#!/bin/bash

function stop_container() {
  echo "Sending SIGTERM to the following processes:"
  echo ""
  for i in /run/watch/*; do
    pid=$(cat $i)
    name=$(cat /proc/$pid/cmdline)
    echo " - $i ($pid) $name"
    kill -TERM $pid
  done
  echo ""
}

trap stop_container SIGTERM
trap stop_container SIGINT

rm -Rf /run/watch
mkdir /run/watch

for i in /etc/init.simple/*; do
  echo "[ STARTING ] $i"
  $i
  if [ $? -ne 0 ]; then
    echo "[ FAILED ] $i"
    exit 1
  fi
done

echo "Supervising watch list: "
echo ""

for i in /run/watch/*; do
  pid=$(cat $i)
  name=$(cat /proc/$pid/cmdline)
  echo " - $i ($pid) $name"
done

echo ""

while [ -e /run/watch/* ]; do
  for i in /run/watch/*; do
    pid=$(cat $i)

    if [ ! -e /proc/$pid ]; then
      echo "[ EXITED ] $i"
      rm $i
      if [ -e /run/watch/* ]; then
        stop_container
      fi
    fi
  done

  sleep 1
done
